[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip LPC845M301JBD48 --probe 1fc9:0132:0F00A019 --defmt"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+

[alias]
rb = "run --bin"
rrb = "run --release --bin"